# Generated by Django 3.2 on 2021-05-17 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vaialable',
            field=models.BooleanField(default=True),
        ),
    ]
